/**
 * Service — the core scoring + tiering steps (engine 04).
 *
 * One exported stub per step of the doc's "Step-by-step job". Bodies are
 * intentionally unimplemented (`// TODO(owner)`); they return typed shapes or
 * throw so the module compiles under strict TS. Prisma models for this engine
 * do NOT exist yet, so they are referenced ONLY in comments.
 *
 * Owned tables (see prisma/schema/scoring-engine.prisma):
 *   scoring_formulas · scoring_formula_versions · account_scores ·
 *   score_history · tier_overrides
 *
 * @see ../../../docs/engines/engine-04-scoring-engine.md
 */

import type { AccountId, Tier, Json } from '../../events';

const NOT_IMPLEMENTED = 'not implemented';

/** A single weighted criterion in a scoring formula. */
export interface ScoringCriterion {
  key: string;
  label: string;
  weight: number; // 0-1, all weights sum to 1
  rationale: string; // Claude's reasoning for this criterion (transparent, editable)
}

/** A versioned, fully-transparent scoring formula generated from the ICP. */
export interface ScoringFormula {
  id: string;
  icp_id: string;
  version: number;
  criteria: ScoringCriterion[];
  /** Default cutoffs: Tier 1 = 70-100, Tier 2 = 40-69, Tier 3 = 10-39. */
  tier_boundaries: { tier1_min: number; tier2_min: number; tier3_min: number };
  /** True when generated by the equal-weight fallback (Claude generation failed). */
  is_fallback: boolean;
}

/** Per-criterion contribution to one account's total score. */
export interface CriterionScore {
  key: string;
  /** Match quality: 1.0 perfect / 0.5 partial / 0.0 no match. */
  match: 0 | 0.5 | 1;
  weight: number;
  contribution: number; // match * weight * 100
}

/** A fully-scored account with its tier and full breakdown. */
export interface ScoredAccount {
  account_id: AccountId;
  total_score: number; // 0-100
  tier: Tier;
  criterion_scores: CriterionScore[];
  formula_version: number;
}

/** Aggregate tier counts for the `accounts.scored` payload. */
export interface TierSummary {
  tier_1_count: number;
  tier_2_count: number;
  tier_3_count: number;
  top_tier_1_account_ids: AccountId[];
}

/**
 * Step 1 — fetch the active formula for this ICP, or generate one via Claude
 * Sonnet 4.6 if none exists. On generation failure, fall back to an equal-weight
 * formula (`is_fallback: true`) and alert the user — never block the pipeline.
 *
 * Reads/writes `scoring_formulas` + `scoring_formula_versions`.
 */
export async function getOrGenerateFormula(
  _workspaceId: string,
  _icpId: string,
): Promise<ScoringFormula> {
  // TODO(owner): SELECT active scoring_formulas row for icpId; if none, call
  // Claude Sonnet 4.6 to generate a weighted formula from the ICP; on failure
  // build the equal-weight fallback. Persist a scoring_formula_versions snapshot.
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * Step 2 (support) — explain the likely tier-distribution impact when a user
 * changes a weight, in plain language (Claude Sonnet 4.6). Backs the live
 * formula-editor preview.
 */
export async function explainFormulaAdjustment(
  _formula: ScoringFormula,
  _changedCriterionKey: string,
): Promise<{ explanation: string }> {
  // TODO(owner): diff the formula, call Claude Sonnet 4.6 for a plain-language impact note.
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * Step 3 — score every account: weighted sum of per-criterion scores
 * (1.0 perfect / 0.5 partial / 0.0 no match), yielding a 0-100 total.
 */
export async function scoreAccounts(
  _accountIds: AccountId[],
  _formula: ScoringFormula,
): Promise<ScoredAccount[]> {
  // TODO(owner): for each account, evaluate every criterion (1.0/0.5/0.0),
  // multiply by weight, sum → total_score (0-100). Tier assigned in step 4.
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * Step 4 — assign tiers using the formula's configurable cutoffs
 * (default Tier 1 = 70-100, Tier 2 = 40-69, Tier 3 = 10-39).
 */
export function assignTiers(
  scored: ScoredAccount[],
  _boundaries: ScoringFormula['tier_boundaries'],
): ScoredAccount[] {
  // TODO(owner): map each total_score → tier using the boundaries.
  return scored;
}

/**
 * Step 5 — apply a manual Tier 1 review override (promote/demote) with a logged,
 * required reason. User override always wins; logged for formula improvement.
 *
 * Writes `tier_overrides`.
 */
export async function applyTierOverride(
  _accountId: AccountId,
  _tier: Tier,
  _reason: string,
  _overriddenBy: string,
): Promise<void> {
  // TODO(owner): INSERT tier_overrides row; reason is required; override wins.
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * Step 5 (support) — analyse patterns in manual demotions to suggest formula
 * improvements (Claude Haiku 4.5 — low-stakes).
 */
export async function analyzeOverridePatterns(
  _workspaceId: string,
  _icpId: string,
): Promise<{ suggestions: string[] }> {
  // TODO(owner): aggregate tier_overrides; ask Claude Haiku 4.5 for formula tweaks.
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * Step 6 — persist a full per-criterion score breakdown for every account
 * (drives the drill-down UI). Writes `account_scores` and appends `score_history`.
 */
export async function storeScoreBreakdowns(
  _workspaceId: string,
  _scored: ScoredAccount[],
): Promise<void> {
  // TODO(owner): UPSERT account_scores (criterion_scores JSONB) + append score_history.
  throw new Error(NOT_IMPLEMENTED);
}

/** Record the tier boundaries actually used for this run (default or user-adjusted). */
export async function recordTierBoundaries(
  _workspaceId: string,
  _formula: ScoringFormula,
): Promise<void> {
  // TODO(owner): persist tier_boundaries on the formula version used for this run.
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * Step 7 (assembly) — compute the tier summary + top Tier 1 ids for the
 * `accounts.scored` payload.
 */
export async function buildTierSummary(
  _scored: ScoredAccount[],
): Promise<{ tier_summary: Json } & TierSummary> {
  // TODO(owner): count accounts per tier; collect top Tier 1 account ids.
  throw new Error(NOT_IMPLEMENTED);
}
